version: "3"
services:
    mariadb:
        build: ./mariadb
        restart: unless-stopped
        container_name: app_mariadb
        ports:
            - "3411:3306"
        volumes:
            - ./mariadb/mariadb_data:/var/lib/mysql
            - ./mariadb/sqls/:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_ROOT_PASSWORD: st123
            MYSQL_DATABASE: sotong
